#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-tram
Version  : 0.8.0
Release  : 8
URL      : https://cran.r-project.org/src/contrib/tram_0.8-0.tar.gz
Source0  : https://cran.r-project.org/src/contrib/tram_0.8-0.tar.gz
Summary  : Transformation Models
Group    : Development/Tools
License  : GPL-2.0
Requires: R-tram-lib = %{version}-%{release}
Requires: R-Formula
Requires: R-basefun
Requires: R-mlt
Requires: R-multcomp
Requires: R-mvtnorm
Requires: R-sandwich
Requires: R-variables
BuildRequires : R-Formula
BuildRequires : R-basefun
BuildRequires : R-mlt
BuildRequires : R-multcomp
BuildRequires : R-mvtnorm
BuildRequires : R-sandwich
BuildRequires : R-variables
BuildRequires : buildreq-R

%description
implemented in package 'mlt'. Available models include Cox models, some parametric 
  survival models (Weibull, etc.), models for ordered categorical variables,
  normal and non-normal (Box-Cox type) linear models, and continuous outcome logistic regression

%package lib
Summary: lib components for the R-tram package.
Group: Libraries

%description lib
lib components for the R-tram package.


%prep
%setup -q -n tram
cd %{_builddir}/tram

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1667526724

%install
export SOURCE_DATE_EPOCH=1667526724
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/tram/CITATION
/usr/lib64/R/library/tram/DESCRIPTION
/usr/lib64/R/library/tram/INDEX
/usr/lib64/R/library/tram/Meta/Rd.rds
/usr/lib64/R/library/tram/Meta/demo.rds
/usr/lib64/R/library/tram/Meta/features.rds
/usr/lib64/R/library/tram/Meta/hsearch.rds
/usr/lib64/R/library/tram/Meta/links.rds
/usr/lib64/R/library/tram/Meta/nsInfo.rds
/usr/lib64/R/library/tram/Meta/package.rds
/usr/lib64/R/library/tram/Meta/vignette.rds
/usr/lib64/R/library/tram/NAMESPACE
/usr/lib64/R/library/tram/NEWS.Rd
/usr/lib64/R/library/tram/R/tram
/usr/lib64/R/library/tram/R/tram.rdb
/usr/lib64/R/library/tram/R/tram.rdx
/usr/lib64/R/library/tram/demo/SCI_ePolr.R
/usr/lib64/R/library/tram/demo/mtram.R
/usr/lib64/R/library/tram/demo/stram.R
/usr/lib64/R/library/tram/demo/undernutrition.R
/usr/lib64/R/library/tram/doc/index.html
/usr/lib64/R/library/tram/doc/mtram.Rnw
/usr/lib64/R/library/tram/doc/mtram.pdf
/usr/lib64/R/library/tram/doc/tram.R
/usr/lib64/R/library/tram/doc/tram.Rnw
/usr/lib64/R/library/tram/doc/tram.pdf
/usr/lib64/R/library/tram/help/AnIndex
/usr/lib64/R/library/tram/help/aliases.rds
/usr/lib64/R/library/tram/help/paths.rds
/usr/lib64/R/library/tram/help/tram.rdb
/usr/lib64/R/library/tram/help/tram.rdx
/usr/lib64/R/library/tram/html/00Index.html
/usr/lib64/R/library/tram/html/R.css
/usr/lib64/R/library/tram/simulations/README.txt
/usr/lib64/R/library/tram/simulations/mtram_sim.R
/usr/lib64/R/library/tram/simulations/sim2d.R
/usr/lib64/R/library/tram/simulations/sim5d.R
/usr/lib64/R/library/tram/tests/Coxph-Ex.R
/usr/lib64/R/library/tram/tests/Coxph-Ex.Rout.save
/usr/lib64/R/library/tram/tests/PI_OVL-Ex.R
/usr/lib64/R/library/tram/tests/Polr-Ex.R
/usr/lib64/R/library/tram/tests/Polr-Ex.Rout.save
/usr/lib64/R/library/tram/tests/Survreg-Ex.R
/usr/lib64/R/library/tram/tests/Survreg-Ex.Rout.save
/usr/lib64/R/library/tram/tests/bugfixes.R
/usr/lib64/R/library/tram/tests/ltmatrices-Ex.R
/usr/lib64/R/library/tram/tests/stram-Ex.R
/usr/lib64/R/library/tram/tests/stram-Ex.Rout.save
/usr/lib64/R/library/tram/undernutrition.RData

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/tram/libs/tram.so
/usr/lib64/R/library/tram/libs/tram.so.avx2
/usr/lib64/R/library/tram/libs/tram.so.avx512
