#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: fbbd4e3
#
Name     : R-tram
Version  : 1.2.1
Release  : 30
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/tram_1.2-1.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/tram_1.2-1.tar.gz
Summary  : Transformation Models
Group    : Development/Tools
License  : GPL-2.0
Requires: R-Formula
Requires: R-basefun
Requires: R-mlt
Requires: R-multcomp
Requires: R-mvtnorm
Requires: R-sandwich
Requires: R-variables
BuildRequires : R-Formula
BuildRequires : R-basefun
BuildRequires : R-mlt
BuildRequires : R-multcomp
BuildRequires : R-mvtnorm
BuildRequires : R-sandwich
BuildRequires : R-variables
BuildRequires : buildreq-R

%description
"Multivariate Conditional Transformation Models"
The two files "sim2d.R" and "sim5d.R" contain simulation code for
reproducing some of the empirical results presented in "Multivariate
Conditional Transformation Models" Alternative implementations with BayesX
and VGAM for the bivariate simulation are included as well, but are
commented out.

%prep
%setup -q -n tram
pushd ..
cp -a tram buildavx2
popd
pushd ..
cp -a tram buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1740523907

%install
export SOURCE_DATE_EPOCH=1740523907
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/tram/CITATION
/usr/lib64/R/library/tram/DESCRIPTION
/usr/lib64/R/library/tram/INDEX
/usr/lib64/R/library/tram/Meta/Rd.rds
/usr/lib64/R/library/tram/Meta/demo.rds
/usr/lib64/R/library/tram/Meta/features.rds
/usr/lib64/R/library/tram/Meta/hsearch.rds
/usr/lib64/R/library/tram/Meta/links.rds
/usr/lib64/R/library/tram/Meta/nsInfo.rds
/usr/lib64/R/library/tram/Meta/package.rds
/usr/lib64/R/library/tram/Meta/vignette.rds
/usr/lib64/R/library/tram/NAMESPACE
/usr/lib64/R/library/tram/NEWS.Rd
/usr/lib64/R/library/tram/R/tram
/usr/lib64/R/library/tram/R/tram.rdb
/usr/lib64/R/library/tram/R/tram.rdx
/usr/lib64/R/library/tram/demo/NAMI.R
/usr/lib64/R/library/tram/demo/SCI_ePolr.R
/usr/lib64/R/library/tram/demo/hcc.R
/usr/lib64/R/library/tram/demo/mtram.R
/usr/lib64/R/library/tram/demo/npb.R
/usr/lib64/R/library/tram/demo/npn.R
/usr/lib64/R/library/tram/demo/stram.R
/usr/lib64/R/library/tram/demo/survtram.R
/usr/lib64/R/library/tram/demo/tram.R
/usr/lib64/R/library/tram/demo/undernutrition.R
/usr/lib64/R/library/tram/doc/index.html
/usr/lib64/R/library/tram/doc/mtram.R
/usr/lib64/R/library/tram/doc/mtram.Rnw
/usr/lib64/R/library/tram/doc/mtram.pdf
/usr/lib64/R/library/tram/doc/tram.R
/usr/lib64/R/library/tram/doc/tram.Rnw
/usr/lib64/R/library/tram/doc/tram.pdf
/usr/lib64/R/library/tram/help/AnIndex
/usr/lib64/R/library/tram/help/aliases.rds
/usr/lib64/R/library/tram/help/paths.rds
/usr/lib64/R/library/tram/help/tram.rdb
/usr/lib64/R/library/tram/help/tram.rdx
/usr/lib64/R/library/tram/html/00Index.html
/usr/lib64/R/library/tram/html/R.css
/usr/lib64/R/library/tram/npnsimulations/README.txt
/usr/lib64/R/library/tram/npnsimulations/dgp.R
/usr/lib64/R/library/tram/npnsimulations/eff_NP_NP.R
/usr/lib64/R/library/tram/npnsimulations/eff_NP_P.R
/usr/lib64/R/library/tram/npnsimulations/eff_P_P.R
/usr/lib64/R/library/tram/npnsimulations/eff_copula.R
/usr/lib64/R/library/tram/npnsimulations/eff_copula_ml.R
/usr/lib64/R/library/tram/npnsimulations/eff_mvord.R
/usr/lib64/R/library/tram/npnsimulations/fit.R
/usr/lib64/R/library/tram/npnsimulations/mkdata.R
/usr/lib64/R/library/tram/npnsimulations/plots.R
/usr/lib64/R/library/tram/npnsimulations/setup.R
/usr/lib64/R/library/tram/npnsimulations/simMakefile
/usr/lib64/R/library/tram/npnsimulations/summary.R
/usr/lib64/R/library/tram/simulations/README.txt
/usr/lib64/R/library/tram/simulations/mtram_sim.R
/usr/lib64/R/library/tram/simulations/sim2d.R
/usr/lib64/R/library/tram/simulations/sim2d.Rout.save
/usr/lib64/R/library/tram/simulations/sim2d.pdf.save
/usr/lib64/R/library/tram/simulations/sim5d.R
/usr/lib64/R/library/tram/simulations/sim5d.Rout.save
/usr/lib64/R/library/tram/simulations/sim5d.pdf.save
/usr/lib64/R/library/tram/tests/Coxph-Ex.R
/usr/lib64/R/library/tram/tests/Coxph-Ex.Rout.save
/usr/lib64/R/library/tram/tests/KaplanMeier-Ex.R
/usr/lib64/R/library/tram/tests/PI_OVL-Ex.R
/usr/lib64/R/library/tram/tests/Polr-Ex.R
/usr/lib64/R/library/tram/tests/Polr-Ex.Rout.save
/usr/lib64/R/library/tram/tests/Survreg-Ex.R
/usr/lib64/R/library/tram/tests/Survreg-Ex.Rout.save
/usr/lib64/R/library/tram/tests/bugfixes.R
/usr/lib64/R/library/tram/tests/intercepts-Ex.R
/usr/lib64/R/library/tram/tests/intercepts-Ex.Rout.save
/usr/lib64/R/library/tram/tests/mmlt-Ex.R
/usr/lib64/R/library/tram/tests/mmlt-Ex.Rout.save
/usr/lib64/R/library/tram/tests/mmlt-interface.R
/usr/lib64/R/library/tram/tests/mtram-Ex.R
/usr/lib64/R/library/tram/tests/mtram-Ex.Rout.save
/usr/lib64/R/library/tram/tests/stram-Ex.R
/usr/lib64/R/library/tram/tests/stram-Ex.Rout.save
/usr/lib64/R/library/tram/undernutrition.RData
